# Generated by Django 4.2.4 on 2023-09-02 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_group', models.CharField(max_length=50)),
                ('p_created', models.DateTimeField(auto_now_add=True)),
                ('p_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'p_group',
                'verbose_name_plural': 'p_groups',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ShopApp')),
                ('price', models.FloatField()),
                ('avaliable', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.pgroup')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
