# Generated by Django 4.2.4 on 2023-09-02 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pgroup',
            options={'verbose_name': 'g_group', 'verbose_name_plural': 'g_groups'},
        ),
        migrations.RenameField(
            model_name='pgroup',
            old_name='p_created',
            new_name='g_created',
        ),
        migrations.RenameField(
            model_name='pgroup',
            old_name='p_updated',
            new_name='g_updated',
        ),
        migrations.AddField(
            model_name='product',
            name='p_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='p_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
