# Generated by Django 4.2.4 on 2023-09-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCartApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elements',
            options={'verbose_name': 'element', 'verbose_name_plural': 'elements'},
        ),
        migrations.AlterModelTable(
            name='elements',
            table='Elements by order',
        ),
    ]
