# Generated by Django 4.2.4 on 2023-08-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='c_content',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='c_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='c_name',
        ),
    ]
